notifications:
  email: false
addons:
  apt:
    packages:
    - libgdal1i
    - gdal-bin
    - libgdal-dev
    - libspatialindex-dev
language: python
# workaround for Python 3.7
# see https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.6
      dist: xenial
      sudo: true
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
install:
  - pip install pipenv
  - travis_retry travis_wait pipenv install

# command to run tests
script: pytest --runslow
